services:
    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - "3500:3500"
        environment:
            NODE_ENV: development
        volumes:
            - backend-db:/app/backend/db
        networks:
            - codecomments-network

    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        ports:
            - "5000:80"
        depends_on:
            - backend
        networks:
            - codecomments-network

volumes:
    backend-db:

networks:
    codecomments-network:
        driver: bridge
