name: Sync Markdown to Wiki
on:
    push:
        branches: [main]
        paths:
            - "docs/code_comments_specs.md"
concurrency:
    group: sync-wiki
    cancel-in-progress: true
permissions:
    contents: write
jobs:
    sync-wiki:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: Andrew-Chen-Wang/github-wiki-action@v4
              with:
                  wiki_token: ${{ secrets.GH_PAT }}
                  repository: ${{ github.repository }}
                  path: .